## SIMPLE NEEDLE
### NEcessary Elements for Deep LEarning
provides
1. CPU backend: `numpy` & GPU backend: `CUDA`
2. Auto Differentiation
3. Initializers & Optimizers

In [2]:
import numpy as np
import python.needle as ndl

x = ndl.initializer.rand_binary((3, 4, 5))
x

needle.Tensor([[[0. 0. 0. 0. 1.]
  [1. 1. 0. 1. 1.]
  [0. 0. 0. 1. 1.]
  [0. 1. 1. 0. 0.]]

 [[1. 1. 0. 0. 0.]
  [1. 1. 0. 0. 1.]
  [1. 1. 1. 0. 0.]
  [1. 0. 0. 1. 0.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 0. 0. 1.]
  [0. 0. 1. 0. 0.]
  [1. 1. 0. 1. 1.]]])

In [8]:
class A:
    def __init__(self, data):
        self.data = data

class B(A):
    pass

a = A(10)
b = B(a)
print(b.data)

In [ ]:
import torch
import torch.nn as nn

a = torch.Tensor([[1, 2], [3, 4]])

In [2]:
import numpy as np

x = np.array([[1, 2, 3], [3, 4, 5]], dtype=np.float32)
y = np.empty((2, 1))

old = (0, 1)
old = None
new = tuple(np.argsort(old))
# origin = [old[i] for i in new]
# origin
x = x > 2

x.data